npm-build-test:
    image: cdn路径
    stage: build
    cache:
        untracked: true
        paths:
            - node_modules/
    before_script:
        - export BI_ENV="test"
    script:
        - "npm install --registry=http://代理地址 --sass_binary_site=https://npm.taobao.org/mirrors/node-sass/"
        - "npm run build"
        - "rsync -auvz dist/index.html  ip::服务器开发分支目录/trunk/resources/views/index/"
        - "rsync -auvz dist/* 静态资源cdn目录/trunk/bi/"
    only:
        - master  分支名称
